# #############################################################################
#
# config.yaml
#
# This is the primary configuration file for the Maypop Labs PRISM project.
# If nothing else, you'll possibly need to change the following:
#
#   rootPath: Change this to the directory where your cellranger_counts folder
#       is located. Results will also be written to this path.
#
#   rcisTargetPath: This is the folder where databases are stored for use by
#       RcisTarget, SCENIC, and GENIE3 in the `07 - GRN - Part 01.R` file.
#
#   ages: This is a vector containing the chronological age of each cell
#       sample.
#
#   donorIDs: This is a vector containing the name for each sample.
#
#   grnScenicSpecies: Only change this if you are using sample from a source
#       other than human. Refer to the online RcisTarget and SCENIC
#       documentation for more details.
#
# #############################################################################

# File Paths
rootPath: "E:/datasets/omics/skin/"
rcisTargetPath: "E:/var/rcistarget"

# Experiment outline
ages:
  - 18
  - 22
  - 23
  - 44
  - 47
  - 48
  - 70
  - 73
  - 76
donorIDs:
  - "18yo"
  - "22yo"
  - "23yo"
  - "44yo"
  - "47yo"
  - "48yo"
  - "70yo"
  - "73yo"
  - "76yo"
  
# Experiment parameters
ageCorrelation: 0.5
cores: 1
saveResults: True
verbose: True

# Plot parameters
figDPI: 300
figHeight: 5
figWidth: 6.5
hjust: 0.5
plotAlpha: 0.75
pointSize: 1.5
strokeSize: 0.33

# Seurat
seuratAssay: "v5"
seuratNumberOfFeatures: 2000

# DEGs
minDEGs: 1000

# SingleR
singleRMinimumNumberOfCells: 1000
singleRNumberOfFeatures: 2000

# Smoothing
winSizePercent: 0.01

# GeneSwitches
geneSwitchesBinarizeCutoff: 0.2
geneSwitchesFDRLevel: 0.05
geneSwitchesMaxDEGs: 100000
geneSwitchesR2Cutoff: 0.1

# Gene regulatory Network (GRN)
grnAddSelfActivation: False
grnPositiveThreshold: 0.7
grnNegativeThreshold: -0.7
grnMergeStronglyConnectedComponents: True
grnOnlyPositiveCorr: False
grnRemoveIsolatedNodes: True
grnRemoveTerminalNodes: False
grnScenicDBs:
  - "hg38__refseq-r80__500bp_up_and_100bp_down_tss.mc9nr.feather"
  - "hg38__refseq-r80__10kb_up_and_down_tss.mc9nr.feather"
grnScenicSpecies: "hgnc"

# Boolean Rules and BoolNet
boolMaxRegulators: 4
boolMinScore: 0.65

# Attractor Analysis
attInitialThreshold: 0.10
nPerturb: 30
nSamplesState: 20








