# #############################################################################
#
# config.yaml
#
# This is the primary configuration file for the Maypop Labs PRISM project.
# If nothing else, you'll possibly need to change the following:
#
#   rootPath: Change this to the directory where your cellranger_counts folder
#       is located. Results will also be written to this path.
#
#   rcisTargetPath: This is the folder where databases are stored for use by
#       RcisTarget, SCENIC, and GENIE3 for GRN creation.
#
#   ages: This is a vector containing the chronological age of each cell
#       sample.
#
#   donorIDs: This is a vector containing the name for each sample.
#
#   grnScenicSpecies: Only change this if you are using sample from a source
#       other than human. Refer to the online RcisTarget and SCENIC
#       documentation for more details.
#
# #############################################################################

# File Paths
rootPath: "E:/datasets/omics/skin/"
rcisTargetPath: "E:/var/rcistarget/"

# Experiment outline
ages:
  - 18
  - 22
  - 23
  - 44
  - 47
  - 48
  - 70
  - 73
  - 76
donorIDs:
  - "18yo"
  - "22yo"
  - "23yo"
  - "44yo"
  - "47yo"
  - "48yo"
  - "70yo"
  - "73yo"
  - "76yo"
  
# Experiment parameters
cores: 1
saveResults: true
verbose: true

# Plot parameters
figDPI: 300
figHeight: 5
figWidth: 6.5
hjust: 0.5
networkLayout: "lgl"
plotAlpha: 0.75
pointSize: 1.5
strokeSize: 0.33
plotBackground: "white"
panelBackground: "white"

# Seurat
seuratMaxPercentMtDNA: 15
seuratMinNumberOfRNAFeatures: 500
seuratNumberOfFeatures: 2000
seuratScaleFactor: 100000

# SingleR
singleRMinimumNumberOfCells: 1000
singleRNumberOfFeatures: 2000

# Pseudotime
pseudotimeMinAgeCorrelation: 0.5

# GeneSwitches
geneSwitchesCutOff: 0.20            # fixed binarization cutoff
geneSwitchesRho: 0.40               # |Spearman| threshold
geneSwitchesMinDetect: 0.05         # ≥5% cells > 0
geneSwitchesVarThreshold: 0.01      # minimal variance
geneSwitchesSpearmanFilter: TRUE    # turn Spearman prefilter on/off
geneSwitchesFixedCutoff: FALSE      # turn on/off global fixed cutoff

# Gene regulatory Network (GRN)
grnFromScratch: FALSE
grnPositiveThreshold: 0.4
grnNegativeThreshold: 0.4
grnOnlyPositiveCorr: FALSE
grnRemoveIsolatedNodes: TRUE
grnScenicDBs:
  - "hg38__refseq-r80__500bp_up_and_100bp_down_tss.mc9nr.feather"
  - "hg38__refseq-r80__10kb_up_and_down_tss.mc9nr.feather"
grnScenicSpecies: "hgnc"
grnCorrWeight: 0.4                    # Weight for correlation score
grnGenie3Weight: 0.4                  # Weight for GENIE3 importance
grnMotifWeight: 0.2                   # Weight for motif confidence
grnHighMotifThreshold: 0.5            # High confidence motif threshold
grnMediumMotifThreshold: 0.2          # Medium confidence motif threshold
grnMotifCorrAlignThreshold: 0.1       # Correlation alignment threshold
grnPriorThreshold: 0.3                # Minimum prior strength to keep weak correlation edges
grnSwitchQualityThreshold: 0.1        # Minimum pseudoR² for switch genes
grnPreserveIntermediates: TRUE        # Keep SCENIC intermediate files
grnCleanupAfterPreservation: TRUE     # Delete original int/ and output/ after preservation

# Boolean Rules and BoolNet
boolCheckpointInterval: 25
boolKValue: 0
boolMaxRegulators: 4
boolMinScore: 0.05
boolMinStates: 10
boolExhaustiveLimit: 20
boolMaxSamples: 1000
boolWeights:
  correlation: 1.0
  motif_confidence: 0.3
  scenic_importance: 0.2
  prior_knowledge: 0.1

# Attractor Analysis
attInitialThreshold: 0.10
nPerturb: 30
nSamplesState: 20
